sudo: false
language: php

php:
    - 7.1
    - 7.2
    - nightly

matrix:
    allow_failures:
        - php: nightly

install:
    - composer self-update
    - composer install

script:
    - composer test-ci